name: Slack DM on run

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    branches: [ "main" ]
  schedule:
    - cron: '40 15 * * 2-4'  # 8:40 AM PDT, Tue–Thu

jobs:
  dm:
    runs-on: ubuntu-latest
    steps:
      - name: Send DM
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "Flywheel Standup meeting in 5\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View run>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK