name: Slack DM (reusable)

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  dm:
    runs-on: ubuntu-latest
    steps:
      - name: Send DM
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "${{ inputs.message }}\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View run>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK